name: CI/CD Keywordia DeployAja

on:
  push:
    branches: [ "master" ]  # CI jalan di main

env:
  REGISTRY: ghcr.io/satriaaa766/keywordia
  IMAGE_NAME: keywordia

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ env.REGISTRY }}:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - uses: actions/checkout@v4
      - uses: deployaja/deployaja-cli@v0.0.10
        with:
          command: deploy
          api-token: ${{ secrets.DEPLOYAJA_TOKEN }}
          additional-args:
            --set container.image=${{ env.REGISTRY }}:${{ github.sha }}
            --set replicas=1
